// @flow

export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST';
export const CHANGE_TAB_REQUEST = 'CHANGE_TAB_REQUEST';
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
export const LOAD_PROFILE_DATA_REQUEST = 'LOAD_PROFILE_DATA_REQUEST';
export const PROFILE_NOT_AUTHORIZED = 'PROFILE_NOT_AUTHORIZED';
export const PROFILE_ERROR = 'PROFILE_ERROR';